// Code generated by "stringer -type ModulationType"; DO NOT EDIT.

package base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Amplitude-1]
	_ = x[Frequency-2]
	_ = x[Phase-3]
	_ = x[DutyCycle-4]
	_ = x[Ratio-5]
	_ = x[Trigger-6]
}

const _ModulationType_name = "NoneAmplitudeFrequencyPhaseDutyCycleRatioTrigger"

var _ModulationType_index = [...]uint8{0, 4, 13, 22, 27, 36, 41, 48}

func (i ModulationType) String() string {
	if i < 0 || i >= ModulationType(len(_ModulationType_index)-1) {
		return "ModulationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ModulationType_name[_ModulationType_index[i]:_ModulationType_index[i+1]]
}
